#!/usr/bin/env bash
# Run this script from the root directory of your project.
# Usage: source setup/export_env

ROOT_DIR=$(pwd)
SRC_DIR="$ROOT_DIR/nscworklog"

# Export PYTHONPATH variable to reflect root and src directories
export PYTHONPATH="$ROOT_DIR:$SRC_DIR"
